### PR TITLE
Product Page MVP Complete

### PR DESCRIPTION
**Pull request by alexmeigz**
- Filter Functionality
- Search Functionality
- Display All Product Given Query

### CODE REVIEW

**Review by pranav01acharya — APPROVED** [review]

**Comment by alexmeigz** [comment]
[Products Page React Component](https://trello.com/c/23xrCgDQ/36-products-page-react-component)

**Comment by alexmeigz** [comment]
[Create All Product View](https://trello.com/c/YwfOPjMj/29-create-all-product-view)

**Comment by alexmeigz** [comment]
[Search Database for Products from Vendors](https://trello.com/c/TZwaM9cX/50-search-database-for-products-from-vendors)

**Comment by alexmeigz** [comment]
[Filter Database for Products from Vendors](https://trello.com/c/LSrf78hM/51-filter-database-for-products-from-vendors)

**Comment by alexmeigz** [comment]
[Form to Create Product](https://trello.com/c/9eWEuRmV/82-form-to-create-product)

**Comment by alexmeigz** [comment]
[Add Caption to Product Model](https://trello.com/c/2xisPxsr/132-add-caption-to-product-model)

**Pull request merged**
