### PR TITLE
Post Display Complete

### PR DESCRIPTION
**Pull request by alexmeigz**

### CODE REVIEW

**Review by yuheho7749 — APPROVED** [review]

**Comment by alexmeigz** [comment]
[Add images and user to posts](https://trello.com/c/6xTDh6W4/140-add-images-and-user-to-posts)

**Comment by alexmeigz** [comment]
[Logged in user can create post](https://trello.com/c/IbRqACer/12-logged-in-user-can-create-post)

**Comment by alexmeigz** [comment]
[Search and Filter Posts](https://trello.com/c/t7c3UkOu/153-search-and-filter-posts)

**Comment by alexmeigz** [comment]
[Recipe Post Display](https://trello.com/c/vPKe8ngg/142-recipe-post-display)

**Comment by alexmeigz** [comment]
[Post Overview Display](https://trello.com/c/YMiKpw9E/141-post-overview-display)

**Comment by alexmeigz** [comment]
[Blog/Review Post Display](https://trello.com/c/dElCkEMN/13-blog-review-post-display)

**Pull request merged**
