### PR TITLE
Joseph ng

### PR DESCRIPTION
**Pull request by yuheho7749**
Implemented Profile display

### CODE REVIEW

**Review by sriya112 — APPROVED** [review]

**Comment by alexmeigz** [comment]
[Implement Private Profile Display](https://trello.com/c/FZHPG0t5/30-implement-private-profile-display)

**Comment by alexmeigz** [comment]
[Integrate Account profile conditional rendering](https://trello.com/c/gVK4XLTz/124-integrate-account-profile-conditional-rendering)

**Comment by alexmeigz** [comment]
[React profile menu](https://trello.com/c/HrMLtRUQ/125-react-profile-menu)

**Comment by alexmeigz** [comment]
[React Main App Conditional Rendering](https://trello.com/c/DLQQuSeE/122-react-main-app-conditional-rendering)

**Comment by alexmeigz** [comment]
[AccountInfoBar React Component](https://trello.com/c/Uo3VFWP2/121-accountinfobar-react-component)

**Pull request merged**
